# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(352, 293)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushMIDI = QtWidgets.QPushButton(self.centralwidget)
        self.pushMIDI.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.pushMIDI.setObjectName("pushMIDI")
        self.listProcess0 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess0.setGeometry(QtCore.QRect(10, 50, 91, 22))
        self.listProcess0.setObjectName("listProcess0")
        self.listProcess1 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess1.setGeometry(QtCore.QRect(10, 80, 91, 22))
        self.listProcess1.setObjectName("listProcess1")
        self.listProcess2 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess2.setGeometry(QtCore.QRect(10, 110, 91, 22))
        self.listProcess2.setObjectName("listProcess2")
        self.listProcess3 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess3.setGeometry(QtCore.QRect(10, 140, 91, 22))
        self.listProcess3.setObjectName("listProcess3")
        self.listProcess4 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess4.setGeometry(QtCore.QRect(10, 170, 91, 22))
        self.listProcess4.setObjectName("listProcess4")
        self.listProcess5 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess5.setGeometry(QtCore.QRect(10, 200, 91, 22))
        self.listProcess5.setObjectName("listProcess5")
        self.listProcess6 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess6.setGeometry(QtCore.QRect(10, 230, 91, 22))
        self.listProcess6.setObjectName("listProcess6")
        self.listProcess7 = QtWidgets.QComboBox(self.centralwidget)
        self.listProcess7.setGeometry(QtCore.QRect(10, 260, 91, 22))
        self.listProcess7.setObjectName("listProcess7")
        self.sliderProcess0 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess0.setEnabled(False)
        self.sliderProcess0.setGeometry(QtCore.QRect(110, 50, 160, 22))
        self.sliderProcess0.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess0.setObjectName("sliderProcess0")
        self.sliderProcess1 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess1.setEnabled(False)
        self.sliderProcess1.setGeometry(QtCore.QRect(110, 80, 160, 22))
        self.sliderProcess1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess1.setObjectName("sliderProcess1")
        self.sliderProcess2 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess2.setEnabled(False)
        self.sliderProcess2.setGeometry(QtCore.QRect(110, 110, 160, 22))
        self.sliderProcess2.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess2.setObjectName("sliderProcess2")
        self.sliderProcess3 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess3.setEnabled(False)
        self.sliderProcess3.setGeometry(QtCore.QRect(110, 140, 160, 22))
        self.sliderProcess3.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess3.setObjectName("sliderProcess3")
        self.sliderProcess4 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess4.setEnabled(False)
        self.sliderProcess4.setGeometry(QtCore.QRect(110, 170, 160, 22))
        self.sliderProcess4.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess4.setObjectName("sliderProcess4")
        self.sliderProcess5 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess5.setEnabled(False)
        self.sliderProcess5.setGeometry(QtCore.QRect(110, 200, 160, 22))
        self.sliderProcess5.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess5.setObjectName("sliderProcess5")
        self.sliderProcess6 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess6.setEnabled(False)
        self.sliderProcess6.setGeometry(QtCore.QRect(110, 230, 160, 22))
        self.sliderProcess6.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess6.setObjectName("sliderProcess6")
        self.sliderProcess7 = QtWidgets.QSlider(self.centralwidget)
        self.sliderProcess7.setEnabled(False)
        self.sliderProcess7.setGeometry(QtCore.QRect(110, 260, 160, 22))
        self.sliderProcess7.setOrientation(QtCore.Qt.Horizontal)
        self.sliderProcess7.setObjectName("sliderProcess7")
        self.processValue0 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue0.setEnabled(False)
        self.processValue0.setGeometry(QtCore.QRect(290, 50, 31, 20))
        self.processValue0.setReadOnly(True)
        self.processValue0.setObjectName("processValue0")
        self.processValue1 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue1.setEnabled(False)
        self.processValue1.setGeometry(QtCore.QRect(290, 80, 31, 20))
        self.processValue1.setReadOnly(True)
        self.processValue1.setObjectName("processValue1")
        self.processValue2 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue2.setEnabled(False)
        self.processValue2.setGeometry(QtCore.QRect(290, 110, 31, 20))
        self.processValue2.setReadOnly(True)
        self.processValue2.setObjectName("processValue2")
        self.processValue3 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue3.setEnabled(False)
        self.processValue3.setGeometry(QtCore.QRect(290, 140, 31, 20))
        self.processValue3.setReadOnly(True)
        self.processValue3.setObjectName("processValue3")
        self.processValue4 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue4.setEnabled(False)
        self.processValue4.setGeometry(QtCore.QRect(290, 170, 31, 20))
        self.processValue4.setReadOnly(True)
        self.processValue4.setObjectName("processValue4")
        self.processValue5 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue5.setEnabled(False)
        self.processValue5.setGeometry(QtCore.QRect(290, 200, 31, 20))
        self.processValue5.setReadOnly(True)
        self.processValue5.setObjectName("processValue5")
        self.processValue6 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue6.setEnabled(False)
        self.processValue6.setGeometry(QtCore.QRect(290, 230, 31, 20))
        self.processValue6.setReadOnly(True)
        self.processValue6.setObjectName("processValue6")
        self.processValue7 = QtWidgets.QLineEdit(self.centralwidget)
        self.processValue7.setEnabled(False)
        self.processValue7.setGeometry(QtCore.QRect(290, 260, 31, 20))
        self.processValue7.setReadOnly(True)
        self.processValue7.setObjectName("processValue7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 50, 47, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 80, 47, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 110, 47, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 140, 47, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 170, 47, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 200, 47, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 230, 47, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(330, 260, 47, 16))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Power Mixer"))
        self.pushMIDI.setText(_translate("MainWindow", "Open MIDI Port"))
        self.label.setText(_translate("MainWindow", "%"))
        self.label_2.setText(_translate("MainWindow", "%"))
        self.label_3.setText(_translate("MainWindow", "%"))
        self.label_4.setText(_translate("MainWindow", "%"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.label_6.setText(_translate("MainWindow", "%"))
        self.label_7.setText(_translate("MainWindow", "%"))
        self.label_8.setText(_translate("MainWindow", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

